### ISSUE TITLE
Tron  离线签名交易

### ISSUE THREAD

**Issue by weihongyang** [stoway/TronNet#1]
{ "code": "TAPOS_ERROR", "message": "VGFwb3MgY2hlY2sgZXJyb3I=" }   报双花问题，请问这个怎么解决

**Comment by stoway** [comment]
贴一下你的代码，我在本地调试下看看

**Comment by weihongyang** [comment]
public async Task TestTransactionSignAsync()
        {
            var privateStr = "8e812436a0e3323166e1f0e8ba79e19e217b2c4a53c970d4cca0cfb1078979df";
            var tronKey = new TronECKey(privateStr, _record.Options.Value.Network);
            var from = tronKey.GetPublicAddress();
            var to = "TGehVcNhud84JDCGrNHKVz9jEAVKUpbuiv";
            var amount = 100_000_000L; // 100 TRX, api only receive trx in Sun, and 1 trx = 1000000 Sun

            var transaction = await CreateTransactionAsync(from, to, amount);

            var transactionExtention = await _wallet.GetTransactionSign2Async(new TransactionSign
            {
                PrivateKey = ByteString.CopyFrom(privateStr.HexToByteArray()),
                Transaction = transaction                
            });
            Assert.NotNull(transactionExtention);

            Assert.True(transactionExtention.Result.Result);

            var transactionSigned = transactionExtention.Transaction;

            var transactionBytes = transaction.ToByteArray();

            var transaction4 = SignTransaction2Byte(transactionBytes, privateStr.HexToByteArray(), transactionSigned);


            var transaction5 = transactionSigned.ToByteArray();

            Assert.Equal(transaction4, transaction5);

            var txidret = _record.TronClient.GetWalletClient().BroadcastTransactionAsync(transactionSigned).GetAwaiter().GetResult().ToString();
            string aaa = txidret;
        }

**Comment by stoway** [comment]
本地生成交易有些问题，你可以先用以下方式实现交易：
```c#
            var transactionClient = _record.ServiceProvider.GetService<ITransactionClient>();
            var walletClient = _record.TronClient.GetWalletClient();
            var privateKey = "8e812436a0e3323166e1f0e8ba79e19e217b2c4a53c970d4cca0cfb1078979df";
            var tronKey = new TronECKey(privateKey, _record.Options.Value.Network);
            var from = tronKey.GetPublicAddress();
            var to = "TGehVcNhud84JDCGrNHKVz9jEAVKUpbuiv";
            var amount = 100_000_000L; // 100 TRX, api only receive trx in Sun, and 1 trx = 1000000 Sun

            var fromAddress = Base58Encoder.DecodeFromBase58Check(from);
            var toAddress = Base58Encoder.DecodeFromBase58Check(to);

            var transaction = await walletClient.CreateTransaction2Async(new TransferContract
            {
                OwnerAddress = ByteString.CopyFrom(fromAddress),
                ToAddress = ByteString.CopyFrom(toAddress),
                Amount = amount,
            });
            
            var transactionSigned = transactionClient.GetTransactionSign(transaction.Transaction, privateKey);

            var result = await transactionClient.BroadcastTransactionAsync(transactionSigned);

            Assert.True(result.Result);

```

**Comment by stoway** [comment]
已在0.1.3版本中解决
