### ISSUE TITLE
GenerateKey function

### ISSUE THREAD

**Issue by masoudchangizi** [stoway/TronNet#10]
There is a sample code like below in your github page but there not GenerateKey() function in the TronClient classs.

        public void GenerateAddress()
        {
            var key = _tronClient.GenerateKey();

            var address = key.GetPublicAddress();
        }

**Comment by stoway** [comment]
> There is a sample code like below in your github page but there not GenerateKey() function in the TronClient classs.
> 
> ```
>     public void GenerateAddress()
>     {
>         var key = _tronClient.GenerateKey();
> 
>         var address = key.GetPublicAddress();
>     }
> ```

Already modified, change code: var key = TronECKey.GenerateKey(TronNetwork.MainNet);
