### ISSUE TITLE
Contract validate error : Smart contract is not exist.

### ISSUE THREAD

**Issue by Kangkejian** [stoway/TronNet#18]
When I use demo with 'TransferAsync',but found some wrong with it!
var contractAddress = "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"; 
wallet.TriggerConstantContract()
{{ "code": "CONTRACT_VALIDATE_ERROR", "message": "Q29udHJhY3QgdmFsaWRhdGUgZXJyb3IgOiBTbWFydCBjb250cmFjdCBpcyBub3QgZXhpc3Qu" }}
Thanks!

**Comment by sqweeezi** [comment]
There is a solution to this problem ?

**Comment by stoway** [comment]
Check your config data:
Mainnet configuration:
services.AddTronNet(x =>
{
x.Network = TronNetwork.MainNet;
x.Channel = new GrpcChannelOption { Host = "grpc.trongrid.io", Port = 50051 };
x.SolidityChannel = new GrpcChannelOption { Host = "grpc.trongrid.io", Port = 50052 };
x.ApiKey = "";
});
see: https://developers.tron.network/docs/trongrid
