### ISSUE TITLE
Corrupted nuget package

### ISSUE THREAD

**Issue by MRayp** [stoway/TronNet#2]
Nuget package seems to be broken and have unresolved dependency to its other projects.
also there is an unnecessary dependency to StowayNet.Extensions.DependencyInjection  project which can be removed and use dotnet core build-in di.

**Comment by stoway** [comment]
please upgrade latest version.

**Comment by stoway** [comment]
> Nuget package seems to be broken and have unresolved dependency to its other projects.
> also there is an unnecessary dependency to StowayNet.Extensions.DependencyInjection project which can be removed and use dotnet core build-in di.

Hello, fix it, please upgrade v0.1.4.
about StowayNet.Extensions.DependencyInjection project, i will solve this problem in the future
