### ISSUE TITLE
Query balance overflow

### ISSUE THREAD

**Issue by miaobei5555** [stoway/TronNet#30]
TRC20ContractClient  

var balance = Convert.ToDecimal(result.Balance);
                if (decimals > 0)
                {
                    balance /= Convert.ToDecimal(Math.Pow(10, decimals));
                }

 Change to

  var balance = Nethereum.Web3.Web3.Convert.FromWeiToBigDecimal(result.Balance);

                return decimal.Parse(balance.ToString());

**Comment by stoway** [comment]
Thanks!
