### ISSUE TITLE
Contract transfer not working properly

### ISSUE THREAD

**Issue by Hossein-79** [stoway/TronNet#31]
I can successfully sign and broadcast TRX transactions and get account balance, but transferring tokens is not working for me.
My code:
```
public async Task<string> TransactionToken(string contractAddress, string privateKey, string toAddress, decimal amount)
{
    try
    {
        var account = _walletClient.GetAccount(privateKey);
        var contractClient = _contractClientFactory.CreateClient(ContractProtocol.TRC20);
        var result = await contractClient.TransferAsync(contractAddress, account, toAddress, amount, string.Empty, 5 * 1000000L);

        return result;
    }
    catch (Exception)
    {
        return null;
        throw;
    }
}
```
I get a txid in the response and it seems that everything's working fine, but the transaction is not happening on the network and I can't find the txid on tronscan.

**Comment by stoway** [comment]
Check your config data:
Mainnet configuration:
services.AddTronNet(x =>
{
    x.Network = TronNetwork.MainNet;
    x.Channel = new GrpcChannelOption { Host = "grpc.trongrid.io", Port = 50051 };
    x.SolidityChannel = new GrpcChannelOption { Host = "grpc.trongrid.io", Port = 50052 };
    x.ApiKey = "";
});
see: https://developers.tron.network/docs/trongrid
