### ISSUE TITLE
Send USDT Not Working

### ISSUE THREAD

**Issue by mahanamiri** [stoway/TronNet#34]
Hello All,
My Code:

```
 IServiceCollection services = new ServiceCollection();
            services.AddTronNet(x =>
            {
                x.Network = TronNetwork.MainNet;
                x.Channel = new GrpcChannelOption { Host = "grpc.trongrid.io"};
                x.SolidityChannel = new GrpcChannelOption { Host = "grpc.trongrid.io"};
                x.ApiKey = "3334986a-****";
            });


            services.AddLogging();

            var service = services.BuildServiceProvider();
            var walletClient = service.GetService<IWalletClient>();

            var account = walletClient.GetAccount(walletPrivateKey);

            //USDT TOKEN
            var contractAddress = "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t";

            //收的錢包
            var to = "TLhTDxNcm9XaSq35mghq6Az35LeHdcn77S";

            var amount = 1;
            //手續費 10 TRX
            var feeAmount = 20 * 1_000_000L;

            var contractClientFactory = service.GetService<IContractClientFactory>();

            var contractClient = contractClientFactory.CreateClient(ContractProtocol.TRC20);

            //備註只能用英文
            var result = contractClient.TransferAsync(contractAddress, account, to, amount, "Test", feeAmount);

            Console.WriteLine("-- RESULT --");
            Console.WriteLine(JsonConvert.SerializeObject(result));
```

 result = Id = 1, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"

**Comment by hy-net** [comment]
The account need to be activated by holding at least 0.000001 TRX before it can receive TRC20 coin

BTW, do we really need 20TRX as transaction fee?? (I am very new to tron as well)

**Comment by Aone8889** [comment]
> Hello All, My Code:
> 
> ```
>  IServiceCollection services = new ServiceCollection();
>             services.AddTronNet(x =>
>             {
>                 x.Network = TronNetwork.MainNet;
>                 x.Channel = new GrpcChannelOption { Host = "grpc.trongrid.io"};
>                 x.SolidityChannel = new GrpcChannelOption { Host = "grpc.trongrid.io"};
>                 x.ApiKey = "3334986a-****";
>             });
> 
> 
>             services.AddLogging();
> 
>             var service = services.BuildServiceProvider();
>             var walletClient = service.GetService<IWalletClient>();
> 
>             var account = walletClient.GetAccount(walletPrivateKey);
> 
>             //USDT TOKEN
>             var contractAddress = "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t";
> 
>             //收的錢包
>             var to = "TLhTDxNcm9XaSq35mghq6Az35LeHdcn77S";
> 
>             var amount = 1;
>             //手續費 10 TRX
>             var feeAmount = 20 * 1_000_000L;
> 
>             var contractClientFactory = service.GetService<IContractClientFactory>();
> 
>             var contractClient = contractClientFactory.CreateClient(ContractProtocol.TRC20);
> 
>             //備註只能用英文
>             var result = contractClient.TransferAsync(contractAddress, account, to, amount, "Test", feeAmount);
> 
>             Console.WriteLine("-- RESULT --");
>             Console.WriteLine(JsonConvert.SerializeObject(result));
> ```
> 
> result = Id = 1, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"

您好您是如何解决的呢
