### ISSUE TITLE
how to transfer trx  from one wallet to other  wallet in asp.net c#

### ISSUE THREAD

**Issue by apal5878** [stoway/TronNet#48]
how to transfer trx  from one wallet to other  wallet in asp.net c# , 
i want  to send tron from one account to other account  , please suggest me help full code script  which i used  in my  asp.net c# project

**Comment by stoway** [comment]
> how to transfer trx from one wallet to other wallet in asp.net c# , i want to send tron from one account to other account , please suggest me help full code script which i used in my asp.net c# project

Hello, you could see TestTransferAsync method: https://github.com/stoway/TronNet/blob/main/test/TronNet.Test/TransactionTest.cs
