### ISSUE TITLE
I can't send usdt from trc20.

### ISSUE THREAD

**Issue by emrealparslan** [stoway/TronNet#49]
Hello,
I can't find where the error is in my work in core 6 :(
I searched many articles and when I finally ran it, the result was "b8107a19cb24e2ffe69b2b45a9499c1bf1bc78f0a54223569a48b6e311df3903". I don't know where to use this incoming information. How do I access the txID? Is this the result of the txID?
I wonder if it is due to the api settings in trongrid.io. Can you help me.

program.cs
builder.Services.AddTronNet(x =>
{
	x.Network = TronNetwork.MainNet;
	x.Channel = new GrpcChannelOption { Host = "grpc.trongrid.io", Port = 50051 };
	x.SolidityChannel = new GrpcChannelOption { Host = "grpc.trongrid.io", Port = 50052 };
	x.ApiKey ="myapikey"
});

TronAccount.cs
namespace .WebUi.Models
{
	public class TronAccount : ITronAccount
        {
            public string PublicKey { get; set; }
            public string PrivateKey { get; set; }
            public string Address { get; set; }
            public byte GetAddressPrefix()
            {
                throw new NotImplementedException();
            }
        }
}

homecontroller.cs
using TronNet;

private readonly IWalletClient _wallet;
private readonly IContractClientFactory _contractClientFactory;

public HomeController( IWalletClient wallet, IContractClientFactory contractClientFactory)
{
	_wallet = wallet;
	_contractClientFactory = contractClientFactory;
}

public async Task<IActionResult> Index()
{
	var privateKey = "8e812436a0e3323166e1f0e8ba79e19e217b2c4a53c970d4cca0cfb1078979df";
	string fromAddress = "TFbrUmaS8Zqdbsw92GDoqx6nH2U9GoosrS";  

	var account = new WebUi.Models.TronAccount()
	{
		Address = fromAddress,
		PrivateKey = privateKey
	};

	var contractAddress = "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"; //USDT Contract Address
	var to = "TDRK6kQnc55EWkFL4bvv8Fefdbt3HfsiE9";
	var amount = 5; //USDT Amount
	var feeAmount = 5 * 1000000L;
	var contractClient = _contractClientFactory.CreateClient(ContractProtocol.TRC20);

	var result = await contractClient.TransferAsync(contractAddress, account, to, amount, string.Empty, feeAmount);
	// result="b8107a19cb24e2ffe69b2b45a9499c1bf1bc78f0a54223569a48b6e311df3903
![2023-05-18_03h41_40](https://github.com/stoway/TronNet/assets/2471467/ee0c528f-e9f9-4948-96b0-8ce05416e0d5)
" 
}

**Comment by stoway** [comment]
> b8107a19cb24e2ffe69b2b45a9499c1bf1bc78f0a54223569a48b6e311df3903

Hello, you could search your Address or TXID in https://tronscan.org/.

I did not find any results based on the info you provided.

if you transfer failed, maybe your feeAmount's amount is too low,  or your trx's balance not enough, check your account.

**Comment by emrealparslan** [comment]
hello, as you said, I increased the numbers but still nothing happened :(
![2023-05-18_15h10_56](https://github.com/stoway/TronNet/assets/2471467/adbf7630-a0eb-452c-ad2b-ba199b10136a)
![2023-05-18_15h04_41](https://github.com/stoway/TronNet/assets/2471467/5e77f015-0988-4c04-9237-a3e98dfb9d34)

**Comment by stoway** [comment]
> hello, as you said, I increased the numbers but still nothing happened :(
> ![2023-05-18_15h10_56](https://github.com/stoway/TronNet/assets/2471467/adbf7630-a0eb-452c-ad2b-ba199b10136a)
> ![2023-05-18_15h04_41](https://github.com/stoway/TronNet/assets/2471467/5e77f015-0988-4c04-9237-a3e98dfb9d34)
> 

continue increase your feeAmount,
var feeAmount = 30 * 1000000L, try it again.

**Comment by emrealparslan** [comment]
I did as you stated but still the same.  f178c6401bd0b1490cb503f0dc34a047775684295e2128f9af1ffd496d88c30f
![2023-05-18_15h25_08](https://github.com/stoway/TronNet/assets/2471467/860f103f-fc63-4035-9497-b342641acb7d)

**Comment by stoway** [comment]
change your config code
x.Channel = new GrpcChannelOption { Host = "grpc.trongrid.io", Port = 50051 };
x.SolidityChannel = new GrpcChannelOption { Host = "grpc.trongrid.io", Port = 50052 };
to:
x.Channel = new GrpcChannelOption { Host = "grpc.shasta.trongrid.io", Port = 50051 };
x.SolidityChannel = new GrpcChannelOption { Host = "grpc.shasta.trongrid.io", Port = 50052 };

**Comment by emrealparslan** [comment]
When I do what you have specified, the null value comes up.
![2023-05-18_16h50_20](https://github.com/stoway/TronNet/assets/2471467/9edb6b51-6a15-4481-8109-38079ba21a59)
![2023-05-18_16h52_01](https://github.com/stoway/TronNet/assets/2471467/f0f7d2d2-945a-4de9-930f-447e2185764c)
 TronNet.Contracts.TRC20ContractClient[0]
      Specified argument was out of the range of valid values. (Parameter 'index')
      System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
         at Google.Protobuf.Collections.RepeatedField`1.get_Item(Int32 index)
         at TronNet.Contracts.TRC20ContractClient.GetDecimals(WalletClient wallet, Byte[] contractAddressBytes)
         at TronNet.Contracts.TRC20ContractClient.TransferAsync(String contractAddress, ITronAccount ownerAccount, String toAddress, Decimal amount, String memo, Int64 feeLimit)

**Comment by emrealparslan** [comment]
I'm so sorry I can't send USDT because I misspelled privatekey.
now working. thanks.

**Comment by Talha613** [comment]
emrealparslan i also can't send usdt can you help me?
