### ISSUE TITLE
按交易哈希查询交易GetTransactionById

### ISSUE THREAD

**Issue by netlocks** [stoway/TronNet#6]
按交易哈希查询交易GetTransactionById，如何解析这个接口返回的数据 我要取得发送地址，接收地址和金额，有偿。
这下面是返回的 要解析parameter.value.data的数据
{
    "ret":[
        {
            "contractRet":"SUCCESS"
        }
    ],
    "signature":[
        "4a7e494686ee3f0e3e288fabee9612a4d83f30b99e4b543b4f5da053dd481b91c35ebdf5568e325136371ed47303a8e6acd1ca419532d77c494636324fb42a7201"
    ],
    "txID":"d1c8d6461bd5a67e79359c27480745329c4f53cb82ff8ee1379f9eaa5dd17709",
    "raw_data":{
        "contract":[
            {
                "parameter":{
                    "value":{
                        "data":"7688415300000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000002710000000000000000000000000af8a80171afcca0a76d33ec56f6e3000bceab5ef0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f09afffc8b64bca573deb35d12ff9b9c69497075",
                        "owner_address":"419e1d445505e6acea6372c69c4afbe6c0c76f8587",
                        "contract_address":"412e598a00d210f294d54bb7b1b8d008558d67d2e7"
                    },
                    "type_url":"type.googleapis.com/protocol.TriggerSmartContract"
                },
                "type":"TriggerSmartContract"
            }
        ],
        "ref_block_bytes":"7497",
        "ref_block_hash":"1fc27e8ca4b6cc9f",
        "expiration":1626706053000,
        "fee_limit":300000000,
        "timestamp":1626705994921
    },
    "raw_data_hex":"0a02749722081fc27e8ca4b6cc9f40888ff2f9ab2f5a9002081f128b020a31747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e54726967676572536d617274436f6e747261637412d5010a15419e1d445505e6acea6372c69c4afbe6c0c76f85871215412e598a00d210f294d54bb7b1b8d008558d67d2e722a4017688415300000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000002710000000000000000000000000af8a80171afcca0a76d33ec56f6e3000bceab5ef0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f09afffc8b64bca573deb35d12ff9b9c6949707570a9c9eef9ab2f900180c6868f01"
}

**Comment by stoway** [comment]
请加微信私聊：mxcoder-net
